const GET_RECIPES = "GET_RECIPES";
const GET_DIETS = "GET_DIETS";
const GET_RECIPE_BY_ID = "GET_RECIPE_BY_ID";
const POST_RECIPE = "POST_RECIPE";
const SET_NAME = "SET_NAME";
const SET_SOURCE = "SET_SOURCE";
const SET_DIET = "SET_DIET";
const SET_SORT = "SET_SORT";
const SET_RECIPES_COPY = "SET_RECIPES_COPY";

module.exports = {
  GET_RECIPES,
  GET_DIETS,
  GET_RECIPE_BY_ID,
  POST_RECIPE,
  SET_NAME,
  SET_SOURCE,
  SET_DIET,
  SET_SORT,
  SET_RECIPES_COPY,
};
