const GET_RECIPES = "GET_RECIPES";
const GET_DIETS = "GET_DIETS";
const GET_RECIPE_BY_NAME = "GET_RECIPE_BY_NAME";
const GET_RECIPE_BY_ID = "GET_RECIPE_BY_ID";
const POST_RECIPE = "POST_RECIPE";
const FILTER_BY_DIETS = "FILTER_BY_DIETS";
const ORDER = "ORDER";

module.exports = {
  GET_RECIPES,
  GET_DIETS,
  GET_RECIPE_BY_ID,
  GET_RECIPE_BY_NAME,
  FILTER_BY_DIETS,
  ORDER,
  POST_RECIPE,
};
